### ISSUE TITLE
Migrate to ASP.NET Core 3.0

### ISSUE THREAD

**Issue by tpeczek** [tpeczek/Demo.AspNetCore.ServerSentEvents#2]

**Comment by dotnetnoobie** [comment]
I have tried to update to 3.0, everything seems to work except I get no message sent to the browser

Have you had any luck working on this yet?  I really am not sure what needs to be done to make it work personally

**Comment by tpeczek** [comment]
@dotnetnoobie 

I'm happy that you've noticed the aspnetcore-v3.0.0 branch. It is using preview packages of Lib.AspNetCore.ServerSentEvents and has been tested with Preview 9 of ASP.NET Core 3.0. Please let me know if you encounter any issues.

**Comment by dotnetnoobie** [comment]
I got it working basically right away using the aspnetcore-v3.0.0 (preview) version

I did not need to change anything in relation to my services for my endpoints or client side code 
I just updated to the aspnetcore-v3.0.0 version and it all worked again as it did before

I am also using VS2019 - Preview 9 of ASP.NET Core 3.0

Thanks

**Comment by tpeczek** [comment]
It's good to hear that @dotnetnoobie :)
